-- Create the table for storing user favorites
CREATE TABLE user_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    track_id TEXT NOT NULL,
    title TEXT,
    artist TEXT,
    artwork TEXT,
    stream_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure a user cannot save the exact same track twice
ALTER TABLE user_favorites ADD CONSTRAINT unique_user_track UNIQUE (username, track_id);

-- Optional: Enable Row Level Security (RLS) if you want to secure the table later
-- ALTER TABLE user_favorites ENABLE ROW LEVEL SECURITY;
